---
server:
  listen_address: "127.0.0.1:8080"
  #config:
  #  read_buffer_size: 16384
akamai:
  host: "https://akamai.example.com"
  client_secret: "your-client-secret"
  client_token: "your-client-token"
  access_token: "your-access-token"

post_purge_request:
  enabled: true
  headers:
    X-Custom-Header: "value"

logs:
  show_access_logs: true
  jwt_user:
    enabled: true
    header: "Cookie"
    jwt_field: "email"
  access_logs_fields:
    - REQUEST:method
    - REQUEST:host
    - REQUEST:path
    - REQUEST:proto
    - REQUEST:referer
    - REQUEST:body

    - REQUEST_HEADER:user-agent
    - REQUEST_HEADER:x-forwarded-for
    - REQUEST_HEADER:x-real-ip

    - RESPONSE:status

    - RESPONSE_HEADER:content-length