---
server:
  listen_address: "127.0.0.1:8080"
akamai:
  host: "https://akamai.example.com"
  client_secret: "your-client-secret"
  client_token: "your-client-token"
  access_token: "your-access-token"
logs:
  show_access_logs: true
  access_logs_fields:
    - REQUEST:method
    - REQUEST:host
    - REQUEST:path
    - REQUEST:proto
    - REQUEST:referer
    - REQUEST:body

    - REQUEST_HEADER:user-agent
    - REQUEST_HEADER:x-forwarded-for
    - REQUEST_HEADER:x-real-ip

    - RESPONSE:status
    - RESPONSE:proto

    - RESPONSE_HEADER:content-length